// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDBEwFUInoO86I4-poFwJoL2hSXlrreg8',
    appId: '1:935115524868:web:cae2f630c67e9ae8ef9e51',
    messagingSenderId: '935115524868',
    projectId: 'smartcampus-dillu-2026-98765',
    authDomain: 'smartcampus-dillu-2026-98765.firebaseapp.com',
    storageBucket: 'smartcampus-dillu-2026-98765.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwogEHso0sWbHhgO40t4JUekHO4KyVLMs',
    appId: '1:935115524868:android:1a1b9aa3ad5293e9ef9e51',
    messagingSenderId: '935115524868',
    projectId: 'smartcampus-dillu-2026-98765',
    storageBucket: 'smartcampus-dillu-2026-98765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf2MzlgoG1beXQN_wBTR7moZBanYaCDZk',
    appId: '1:935115524868:ios:669444bfb5a45cb9ef9e51',
    messagingSenderId: '935115524868',
    projectId: 'smartcampus-dillu-2026-98765',
    storageBucket: 'smartcampus-dillu-2026-98765.firebasestorage.app',
    iosBundleId: 'com.example.smartcampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf2MzlgoG1beXQN_wBTR7moZBanYaCDZk',
    appId: '1:935115524868:ios:669444bfb5a45cb9ef9e51',
    messagingSenderId: '935115524868',
    projectId: 'smartcampus-dillu-2026-98765',
    storageBucket: 'smartcampus-dillu-2026-98765.firebasestorage.app',
    iosBundleId: 'com.example.smartcampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDBEwFUInoO86I4-poFwJoL2hSXlrreg8',
    appId: '1:935115524868:web:6b7cf86a6b52d336ef9e51',
    messagingSenderId: '935115524868',
    projectId: 'smartcampus-dillu-2026-98765',
    authDomain: 'smartcampus-dillu-2026-98765.firebaseapp.com',
    storageBucket: 'smartcampus-dillu-2026-98765.firebasestorage.app',
  );
}
